name: Auto Reply to New Issues

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  auto-comment:
    name: Post welcome comment
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request == null }}
    steps:
      - name: Add welcome comment
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.payload.issue.number;
            const body = `Thank you for raising this issue! Our team will review it soon. For more queries or discussions or approval of requests, please join the Discord server for further discussion: [Discord Link](https://discord.com/invite/Yn9g6KuWyA)`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body
            });
